In [13]:
import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = (
    r"G:\My Drive\Spacesmith and Wordsmith's Tower\Spacesmith's HQ"
    r"\Nuclear Energy and Propulsion Engineering\Accenture AI-ML Computational Scientist"
    r"\Credentials\gen-lang-client-0137385761-b0d89e37e8e5.json"
)

In [14]:
from google.cloud import bigquery
from google.oauth2 import service_account

# Google Cloud credentials
credentials = service_account.Credentials.from_service_account_file(

    r"G:\My Drive\Spacesmith and Wordsmith's Tower\Spacesmith's HQ\Nuclear Energy and Propulsion Engineering\Accenture AI-ML Computational Scientist\Credentials\gen-lang-client-0137385761-b0d89e37e8e5.json"

)

# Client
client = bigquery.Client(project="gen-lang-client-0137385761", credentials=credentials)

# Construct a reference to the "hacker_news" dataset
dataset_ref = client.dataset("hacker_news", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

# Construct a reference to the "full" table
table_ref = dataset_ref.table("full")

# API request - fetch the table
table = client.get_table(table_ref)

# Preview the first five lines of the table
client.list_rows(table, max_results=5).to_dataframe()

,title,url,text,dead,by,score,time,timestamp,type,id,parent,descendants,ranking,deleted
0,"The loss of OnePlus in the US will sting but, ...",https://9to5google.com/2026/03/29/oneplus-us-w...,NaN,<NA>,neogodless,4,1774881723,2026-03-30 14:42:03+00:00,story,47575001,<NA>,0,<NA>,<NA>
1,IHP Haskell Framework v1.5 has been released,https://github.com/digitallyinduced/ihp/releas...,NaN,<NA>,_query,6,1774881814,2026-03-30 14:43:34+00:00,story,47575018,<NA>,0,<NA>,<NA>
2,PicoUnits: Lightweight units and DSL for scien...,https://github.com/wgbowley/PicoUnits,NaN,<NA>,wgbowley,2,1774881879,2026-03-30 14:44:39+00:00,story,47575030,<NA>,1,<NA>,<NA>
3,"In Case of Emergency, Make Burrito Bison 3 (2017)",https://juicybeast.com/2017/08/03/in-case-of-e...,NaN,<NA>,amarcheschi,27,1774881935,2026-03-30 14:45:35+00:00,story,47575039,<NA>,8,<NA>,<NA>
4,Show HN: Building a GPT from scratch: What I l...,https://twitter.com/pirosb3/status/20383745029...,NaN,<NA>,pirosb3,2,1774881943,2026-03-30 14:45:43+00:00,story,47575041,<NA>,0,<NA>,<NA>

In [15]:
# Query to select comments that received more than 10 replies
query_popular = """
                SELECT parent, COUNT(id)
                FROM `bigquery-public-data.hacker_news.full`
                GROUP BY parent
                HAVING COUNT(id) > 10
                """

# Set up the query (cancel the query if it would use too much of 
# your quota, with the limit set to 10 GB)
safe_config = bigquery.QueryJobConfig(maximum_bytes_billed=10**10)
query_job = client.query(query_popular, job_config=safe_config)

# API request - run the query, and convert the results to a pandas DataFrame
popular_comments = query_job.to_dataframe(create_bqstorage_client=False)

# Print the first five rows of the DataFrame
print(query_job)
popular_comments.head()

QueryJob<project=gen-lang-client-0137385761, location=US, id=410dcc8b-a43a-4f03-ba8a-59b1fc9113c7>

     parent  f0_
0  46751542   49
1  30329762   65
2  30333956   59
3  30356177   53
4  30361850   52

In [16]:
# Query to select comments that received more than 10 replies
query_popular = """
                SELECT parent, COUNT(id) AS NumPosts
                FROM `bigquery-public-data.hacker_news.full`
                GROUP BY parent
                HAVING COUNT(id) > 10
                """

# Set up the query (cancel the query if it would use too much of 
# your quota, with the limit set to 10 GB)
safe_config = bigquery.QueryJobConfig(maximum_bytes_billed=10**10)
query_job = client.query(query_popular, job_config=safe_config)

# API request - run the query, and convert the results to a pandas DataFrame
popular_comments = query_job.to_dataframe(create_bqstorage_client=False)

# Print the first five rows of the DataFrame
popular_comments.head()

     parent  NumPosts
0   1608315        57
1  16468196       106
2  16554019        41
3  32261868        70
4  32266086        75

In [ ]:
# Improved version of earlier query, now with aliasing & improved readability
query_improved = """
                 SELECT parent, COUNT(1) AS NumPosts
                 FROM `bigquery-public-data.hacker_news.full`
                 GROUP BY parent
                 HAVING COUNT(1) > 10
                 """

safe_config = bigquery.QueryJobConfig(maximum_bytes_billed=10**10)
query_job = client.query(query_improved, job_config=safe_config)

# API request - run the query, and convert the results to a pandas DataFrame
improved_df = query_job.to_dataframe(create_bqstorage_client=False)

# Print the first five rows of the DataFrame
improved_df.head()