In [13]:
import pandas as pd

In [14]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

In [15]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

In [16]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

In [17]:
# Series
pd.Series([1, 2, 3, 4, 5])

# A Series is, in essence, a single column of a DataFrame.
# So you can assign row labels to the Series the same way as before, using an index parameter.
# However, a Series does not have a column name, it only has one overall name:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [18]:
# Reading data files
# Being able to create a DataFrame or Series by hand is handy. 
# But, most of the time, we won't actually be creating our own data by hand. 
# Instead, we'll be working with data that already exists.
# Data can be stored in any of a number of different forms and formats. 
# By far the most basic of these is the humble CSV file. 
# When you open a CSV file you get something that looks like this:
ingredients = pd.Series(['4 cups', '1 cup', '2 large', '1 can'], index=['Flour', 'Milk', 'Eggs', 'Spam'], name='Dinner')

In [19]:
import pandas as pd

# Create a DataFrame with 5 items. The index will automatically be 0, 1, 2, 3, 4.
data = {'Fruit': ['Apples', 'Bananas', 'Cherries', 'Dates', 'Elderberries']}
df = pd.DataFrame(data)

print("--- Original DataFrame ---")
print(df)
print("\n")

print("--- Using .iloc[0:3] (Exclusive) ---")
# .iloc excludes the final number, just like standard Python lists.
# This grabs positions 0, 1, and 2. (Returns 3 entries)
print(df.iloc[0:3])
print("\n")

print("--- Using .loc[0:3] (Inclusive) ---")
# .loc includes the final label.
# This grabs the rows labeled 0, 1, 2, AND 3. (Returns 4 entries)
print(df.loc[0:3])

--- Original DataFrame ---
          Fruit
0        Apples
1       Bananas
2      Cherries
3         Dates
4  Elderberries


--- Using .iloc[0:3] (Exclusive) ---
      Fruit
0    Apples
1   Bananas
2  Cherries


--- Using .loc[0:3] (Inclusive) ---
      Fruit
0    Apples
1   Bananas
2  Cherries
3     Dates